[strings]
test_key = "test_value"

[numbers]
counter = 6
new_counter = 2
another_counter = -1
checkpoint_count = 1

[flags]
enabled = true

[metadata]
session_id = "cbc24eab-a5cd-4deb-94df-7d17b50a8180"
created_at = "2025-07-31T09:46:21.276900426Z"
updated_at = "2025-07-31T09:47:51.559059548Z"
readme_read = true
