# b00t-mcp MCP Server Configuration
# For use with b00t-cli mcp commands

name = "b00t-mcp"
description = "MCP server for b00t-cli command proxy with ACL filtering"

[mcp_config]
command = "b00t-mcp"
args = ["--stdio"]
env = {}

# Optional working directory (defaults to ~/.dotfiles)
# cwd = "/home/user/.dotfiles"