# https://github.com/Zenika/alpine-chrome
FROM zenika/alpine-chrome:with-node


# Set the command to run Chrome
CMD ["chromium-browser", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222", "--headless", "--no-sandbox"]

