[b00t]
name = "anthropic"
type = "ai"
hint = "Anthropic Claude models via official API"

[models.claude-3-haiku-20240307]
capabilities = "text,vision"
context_length = 200000
cost_per_1k_input_tokens = 0.00025
cost_per_1k_output_tokens = 0.00125
max_tokens = 4096

[models.claude-3-5-sonnet-20241022]
capabilities = "text,vision,artifacts,computer_use"
context_length = 200000
cost_per_1k_input_tokens = 0.003
cost_per_1k_output_tokens = 0.015
max_tokens = 8192

[env]
ANTHROPIC_API_BASE = "https://api.anthropic.com"
ANTHROPIC_API_KEY = "${ANTHROPIC_API_KEY}"
