[b00t]
name = "brave-search"
type = "mcp"
hint = "Brave Search API integration"

[[b00t.mcp.stdio]]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-brave-search"]
transport = "stdio"
priority = 0
requires = ["node"]
