[b00t]
name = "filesystem"
type = "mcp"
hint = "MCP server"

[[b00t.mcp.stdio]]
args = ["-y", "@modelcontextprotocol/server-filesystem"]
command = "npx"
requires = ["node"]
priority = 0
transport = "stdio"
