

[b00t]
name = "gh"
desires = "2.74.2"
install = """
curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
&& sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
&& sudo apt update \
&& sudo apt install gh -y
"""
update = "sudo apt update && sudo apt install gh -y"
version = "gh --version"
version_regex = "\\d+\\.\\d+\\.\\d+"
hint = "gh is the official GitHub CLI, for interacting with GitHub from the command line."

