[b00t]
name = "git-cliff"
desires = "2.9.1"
install = '''
cargo install git-cliff --force
'''
version = "git cliff --version"
version_regex = '\d+\.\d+\.\d+'
hint = "git-cliff generates changelogs from conventional commits. Run `git-cliff -p` to preview the changelog."

