[b00t]
name = "github"
type = "mcp"
hint = "GitHub MCP server"

[[b00t.mcp.stdio]]
priority = 0
command = "npx"
requires = ["node"]
transport = "stdio"
args = ["-y", "@modelcontextprotocol/server-github"]
