[b00t]
name = "github"
type = "mcp"
hint = "GitHub MCP server for repository management"

[[b00t.mcp.stdio]]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-github"]
transport = "stdio"
priority = 0
requires = ["node"]
