[b00t]
name = "github"
type = "mcp"
hint = "This is a sample MCP server configuration with comments The dwiw flag will strip these comments automatically GitHub MCP server for repository management"
command = "npx"
args = ["-y", "@modelcontextprotocol/server-github"]
