[b00t]
name = "just-mcp"
type = "mcp"
hint = "Justfile MCP server"

[[b00t.mcp.stdio]]
command = "/home/brianh/promptexecution/devx/just-awesome/just-mcp/target/release/just-mcp"
args = ["--stdio"]
transport = "stdio"
priority = 0
requires = []
