[b00t]
name = "lsp"
type = "mcp"
hint = "Language Server Protocol via Docker - Provides LSP functionality through Docker container"

[[b00t.stdio]]
command = "docker"
args = ["run", "-i", "--rm", "docker.io/jonrad/lsp-mcp:0.3.1"]
transport = "stdio"
priority = 0
requires = ["docker"]