[b00t]
name = "openai"
type = "ai"
hint = "OpenAI GPT models via official API"

[models.gpt-4-turbo]
capabilities = "text,chat,vision,json"
context_length = 128000
cost_per_1k_tokens = 0.01
max_tokens = 4096

[models."gpt-3.5-turbo"]
capabilities = "text,chat,json"
context_length = 16384
cost_per_1k_tokens = 0.001
max_tokens = 4096

[models.gpt-4]
capabilities = "text,chat,vision"
context_length = 8192
cost_per_1k_tokens = 0.03
max_tokens = 4096

[env]
OPENAI_API_BASE = "https://api.openai.com/v1"
OPENAI_API_KEY = "${OPENAI_API_KEY}"
