[b00t]
name = "playwright"
type = "mcp"
hint = "Playwright MCP server for browser automation"

[[b00t.stdio]]
command = "npx"
args = ["@playwright/mcp@latest"]
transport = "stdio"
priority = 0
requires = ["node"]
