[b00t]
name = "postgres-enhanced"
type = "docker"
hint = "PostgreSQL database with enhanced configuration and resource management"
desires = "16-alpine"
keywords = ["database", "postgres", "sql", "persistence"]

# Enhanced Docker fields
image = "postgres:16-alpine"
oci_uri = "docker.io/library/postgres:16-alpine"
resource_path = "docker.🐳/postgres-stack"  # Points to docker-compose.yml in _b00t_/docker.🐳/

# Optional traditional docker_args for single container mode
docker_args = [
    "-e", "POSTGRES_PASSWORD=password",
    "-e", "POSTGRES_DB=testdb", 
    "-p", "5432:5432",
    "-v", "postgres_data:/var/lib/postgresql/data"
]

# Environment variables
[b00t.env]
POSTGRES_PASSWORD = ""
POSTGRES_DB = "testdb"
POSTGRES_PORT = "5432"
POSTGRES_VERSION = "16-alpine"