[b00t]
name = "postgres-dev-stack"
type = "stack"
hint = "Full PostgreSQL development environment with pgAdmin and Redis"

# Stack members - datums that will be installed together
members = [
    "postgres-enhanced.docker",
    "pgadmin.docker",
    "redis.docker",
]

# Environment variables shared across all stack members
[env]
POSTGRES_PASSWORD = "${POSTGRES_PASSWORD:-devpassword}"
POSTGRES_USER = "${POSTGRES_USER:-postgres}"
POSTGRES_DB = "${POSTGRES_DB:-devdb}"
PGADMIN_DEFAULT_EMAIL = "${PGADMIN_EMAIL:-admin@localhost}"
PGADMIN_DEFAULT_PASSWORD = "${PGADMIN_PASSWORD:-admin}"
REDIS_PASSWORD = "${REDIS_PASSWORD:-}"
