[b00t]
name = "anthropic"
type = "ai"
hint = "Anthropic Claude models via official API"

[models]
"claude-3-5-sonnet-20241022" = { "context_length" = 200000, "cost_per_1k_input_tokens" = 0.003, "cost_per_1k_output_tokens" = 0.015, "capabilities" = "text,vision,artifacts,computer_use", "max_tokens" = 8192 }
"claude-3-haiku-20240307" = { "context_length" = 200000, "cost_per_1k_input_tokens" = 0.00025, "cost_per_1k_output_tokens" = 0.00125, "capabilities" = "text,vision", "max_tokens" = 4096 }

[env]
ANTHROPIC_API_KEY = "${ANTHROPIC_API_KEY}"
ANTHROPIC_API_BASE = "https://api.anthropic.com"