# syntax=docker/dockerfile:1

##* * * * * \\
# 🐳 Docker
# 👾 Google Layer
# 层 (Céng) Layer
##* * * * * //

# install gcp-cli

# snap install google-cloud-sdk --classic
# gcloud init

pull gcr.io/google.com/cloudsdktool/cloud-sdk:latest


# Google Sheets Scriping Starter Pack

https://github.com/niieani/google-sheets-scripting-starter-pack
