# safely initialize _b00t_ bash
if [ `type -t "_b00t_init_🚀_开始"` == "function" ]; then 
    # detect _b00t_ environment 
    _b00t_init_🚀_开始
fi



## * * * * * * * * * * * \\
#*
#* Purpose: ⚠️ THIS IS AN EXAMPLE/TEMPLATE! (code in here doesn't run)
#*
## * * * * * * * * * * * //

RUN /c0de/_b00t/bash/AZ_bicep_init.🤖.sh


## * * * * \\
# Example Function
my_function () {
  echo "some result"
  return 55
}
my_function
echo $?
## * * * * //





function_name () {
  commands
}


