model_list:
  # https://docs.litellm.ai/docs/providers/vllm
  # - model_name: my-model
  #   litellm_params:
  #     model: hosted_vllm/facebook/opt-125m  # add hosted_vllm/ prefix to route as OpenAI provider
  #     api_base: https://hosted-vllm-api.co      # add api base for OpenAI compatible provider
  #
  - model_name: fireworks-llama-v3p1-8b-instruct
    litellm_params:
      model: fireworks_ai/accounts/fireworks/models/llama-v3p1-8b-instruct
      api_key: "os.environ/FIREWORKS_AI_API_KEY"
  - model_name: fireworks-llama-v3-70b-instruct
    litellm_params:
      model: fireworks_ai/accounts/fireworks/models/llama-v3-70b-instruct
      api_key: "os.environ/FIREWORKS_AI_API_KEY"
  - model_name: fireworks-deepseek-v3
    litellm_params:
      model: fireworks_ai/accounts/fireworks/models/deepseek-v3
      api_key: "os.environ/FIREWORKS_AI_API_KEY"

general_settings:
  master_key: sk-1234      # enter your own master key, ensure it starts with 'sk-'
  # alerting: ["slack"]      # Setup slack alerting - get alerts on LLM exceptions, Budget Alerts, Slow LLM Responses
  # proxy_batch_write_at: 60 # Batch write spend updates every 60s
  # database_connection_pool_limit: 10 # limit the number of database connections to = MAX Number of DB Connections/Number of instances of litellm proxy (Around 10-20 is good number)

  # OPTIONAL Best Practices
  # disable_spend_logs: True # turn off writing each transaction to the db. We recommend doing this is you don't need to see Usage on the LiteLLM UI and are tracking metrics via Prometheus
  # disable_error_logs: True # turn off writing LLM Exceptions to DB
  # allow_requests_on_db_unavailable: True # Only USE when running LiteLLM on your VPC. Allow requests to still be processed even if the DB is unavailable. We recommend doing this if you're running LiteLLM on VPC that cannot be accessed from the public internet.

litellm_settings:
  request_timeout: 600    # raise Timeout error if call takes longer than 600 seconds. Default value is 6000seconds if not set
  set_verbose: False      # Switch off Debug Logging, ensure your logs do not have any debugging on
  json_logs: true         # Get debug logs in json format


