name: Dispatch Downstream Sync

on:
  push:
    branches:
      - main

jobs:
  dispatch-downstream:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger downstream sync workflow
        env:
          DOWNSTREAM_PAT: ${{ secrets.DOWNSTREAM_PAT }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $DOWNSTREAM_PAT" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/elasticdotventures/_b00t_/actions/workflows/sync.yml/dispatches \
            -d '{"ref":"main"}'
